version: "3.9"
services:
    server:
        build: .
        container_name: debug_django_test1
        ports:
            - "8000:8000"
        volumes:
            - ./:/gypso_app
        command: python manage.py runserver 0.0.0.0:8000